### ISSUE TITLE
rework create invoice

### ISSUE THREAD

**Issue by kuroYXDE** [DevelappersGmbH/BillomatNet#209]
add to create a single invoice item to an existing invoice and rework the create invoice method

**Comment by martinhey** [comment]
@kuroYXDE was genau ist damit gemeint?

**Comment by kuroYXDE** [comment]
Bis jetzt können wir nur eine Rechnung erstellen, in der schon Positionen übergeben werden können.
Da will ich also machen, dass auch Positionen im nachhinein zu einer Rechnung erstellt werden können.

Bei der Methode zum erstellen von Rechnungen würde ich nur kleine Änderungen machen. Z. B. bei dem Parametern statt 'invoice' 'model' schreiben und bei der ArgumentException einen kleinen Text schreiben.

**Comment by martinhey** [comment]
das erste ist ein Duplikat von #46 - also bitte darunter bearbeiten

**Comment by martinhey** [comment]
die Anpassung der Texte und des Parameters ist ok
